require_relative "../app/models/vertex.rb"
require_relative "../app/models/vector.rb"
require_relative "../app/models/facet.rb"
require_relative "../app/models/solid.rb"
require_relative "../lib/stl_parser.rb"